### ISSUE TITLE
 motor x axis continuous movement scan and triggering

### ISSUE THREAD

**Issue by Relm-Arrowny** [stan-dot/j20-bluesky#11]
> the first would be the plan for the t5 (?) motor x axis continuous movement scan and triggering

The motor x is TS X motor with epic PV  "BL20J-OP-PCHRO-01:TS:XFINE"

### Goals
- [ ]   Trajectory scan:
           A trajectory scan is where during a Trajectory movement the detector is triggered by a TTL signal coming from the Zebra box.
- [ ]  Data from the scan should be put back together in a meaningful way, e.g. when detector was triggered the TS X is at position x where x is the actual position of the slit at the time. 

### Tasks
- [ ] Decide the performance require, e.g. what working mean?
- [ ] Create a device that can move TS X motor in a define trajectory #10 
- [ ] #12
- [ ] Synchronise the data output.
- [ ] Write test and do test.

**Comment by stan-dot** [comment]
Depends on #10
